export const packages = [
    {
      id: 1,
      title: "Char Dham Yatra",
      image: "/chardham.webp",
      alt: "Char Dham",
      days: "12 Days / 11 Nights",
      description:
        "Complete the sacred pilgrimage to Yamunotri, Gangotri, Kedarnath, and Badrinath in the Himalayas.",
      groupSize: "15-20 people",
      location: "Uttarakhand",
      price: "₹45,999",
      originalPrice: "₹52,999",
      highlight: "Sacred pilgrimage in the Himalayas",
      tag: "Best Seller",
      delay: 0.1,
      gradient: "from-red-900/70",
    },
    {
      id: 2,
      title: "Golden Triangle with Varanasi",
      image: "/GoldenTriangle.png",
      alt: "Golden Triangle",
      days: "8 Days / 7 Nights",
      description:
        "Explore Delhi, Agra, Jaipur, and the spiritual city of Varanasi in one comprehensive tour.",
      groupSize: "10-15 people",
      location: "Delhi, UP, Rajasthan",
      price: "₹32,499",
      originalPrice: "₹38,999",
      highlight: "Explore India's cultural triangle",
      delay: 0.2,
      gradient: "from-amber-900/70",
    },
    {
      id: 3,
      title: "Himalayan Hill Station Retreat",
      image: "/HimalayanHillStation.jpg",
      alt: "Himalayan Retreat",
      days: "10 Days / 9 Nights",
      description:
        "Rejuvenate your soul with a peaceful retreat to Shimla, Manali, and Dharamshala.",
      groupSize: "8-12 people",
      location: "Himachal Pradesh",
      price: "₹38,499",
      originalPrice: "₹42,999",
      highlight: "Peaceful mountain retreat",
      delay: 0.3,
      gradient: "from-green-900/70",
    },
  ];
  